export const coursesAndPrograms = [
    { value: "Bachelor in Accountancy", text: "Bachelor in Accountancy" },
    { value: "Bachelor in Advertising", text: "Bachelor in Advertising" },
    { value: "Bachelor in Advertising And Public Relation", text: "Bachelor in Advertising And Public Relation" },
    { value: "Bachelor in Agro-Forestry Technology", text: "Bachelor in Agro-Forestry Technology" },
    { value: "Bachelor in Applied Deaf Studies", text: "Bachelor in Applied Deaf Studies" },
    { value: "Bachelor in Applied Economics", text: "Bachelor in Applied Economics" },
    { value: "Bachelor in Applied Science", text: "Bachelor in Applied Science" },
    { value: "Bachelor in Banking And Finance", text: "Bachelor in Banking And Finance" },
    { value: "Bachelor in Broadcast Communications", text: "Bachelor in Broadcast Communications" },
    { value: "Bachelor in Business Administration", text: "Bachelor in Business Administration" },
    { value: "Bachelor in Business Engineering", text: "Bachelor in Business Engineering" },
    { value: "Bachelor in Business Journalism", text: "Bachelor in Business Journalism" },
    { value: "Bachelor in Business Management", text: "Bachelor in Business Management" },
    { value: "Bachelor in Business Teacher Education", text: "Bachelor in Business Teacher Education" },
    { value: "Bachelor in Commercial Science", text: "Bachelor in Commercial Science" },
    { value: "Bachelor in Computer Data Processing Management", text: "Bachelor in Computer Data Processing Management" },
    { value: "Bachelor in Computer Management", text: "Bachelor in Computer Management" },
    { value: "Bachelor in Computer Technology", text: "Bachelor in Computer Technology" },
    { value: "Bachelor in Cooperative", text: "Bachelor in Cooperative" },
    { value: "Bachelor in Entrepreneurial Management", text: "Bachelor in Entrepreneurial Management" },
    { value: "Bachelor in Human Behavior Technology", text: "Bachelor in Human Behavior Technology" },
    { value: "Bachelor in Industrial Psychology", text: "Bachelor in Industrial Psychology" },
    { value: "Bachelor in Industrial Technology", text: "Bachelor in Industrial Technology" },
    { value: "Bachelor in Information Technology", text: "Bachelor in Information Technology" },
    { value: "Bachelor in Inter-Disciplinary Studies", text: "Bachelor in Inter-Disciplinary Studies" },
    { value: "Bachelor in Journalism", text: "Bachelor in Journalism" },
    { value: "Bachelor in Library And Information Science", text: "Bachelor in Library And Information Science" },
    { value: "Bachelor in Office Administration", text: "Bachelor in Office Administration" },
    { value: "Bachelor in Performing Arts", text: "Bachelor in Performing Arts" },
    { value: "Bachelor in Physical Education", text: "Bachelor in Physical Education" },
    { value: "Bachelor in Pilipino", text: "Bachelor in Pilipino" },
    { value: "Bachelor in Political Economy", text: "Bachelor in Political Economy" },
    { value: "Bachelor in Tourism", text: "Bachelor in Tourism" },
    { value: "Bachelor in Transportation Management", text: "Bachelor in Transportation Management" },
    { value: "Bachelor of Agricultural Entrepreneurship", text: "Bachelor of Agricultural Entrepreneurship" },
    { value: "Bachelor of Agricultural Technology", text: "Bachelor of Agricultural Technology" },
    { value: "Bachelor of Arts", text: "Bachelor of Arts" },
    { value: "Bachelor of Arts in Anthropology", text: "Bachelor of Arts in Anthropology" },
    { value: "Bachelor of Arts in Applied Psychology", text: "Bachelor of Arts in Applied Psychology" },
    { value: "Bachelor of Arts in Applied Sociology", text: "Bachelor of Arts in Applied Sociology" },
    { value: "Bachelor of Arts in Asian Studies", text: "Bachelor of Arts in Asian Studies" },
    { value: "Bachelor of Arts in Basic Medical Science", text: "Bachelor of Arts in Basic Medical Science" },
    { value: "Bachelor of Arts in Behavioral Science", text: "Bachelor of Arts in Behavioral Science" },
    { value: "Bachelor of Arts in Broadcast Communication", text: "Bachelor of Arts in Broadcast Communication" },
    { value: "Bachelor of Arts in College Teaching", text: "Bachelor of Arts in College Teaching" },
    { value: "Bachelor of Arts in Commerce", text: "Bachelor of Arts in Commerce" },
    { value: "Bachelor of Arts in Communication", text: "Bachelor of Arts in Communication" },
    { value: "Bachelor of Arts in Communication Arts", text: "Bachelor of Arts in Communication Arts" },
    { value: "Bachelor of Arts in Comparative Literature", text: "Bachelor of Arts in Comparative Literature" },
    { value: "Bachelor of Arts in Computer Science", text: "Bachelor of Arts in Computer Science" },
    { value: "Bachelor of Arts in Computer Teaching", text: "Bachelor of Arts in Computer Teaching" },
    { value: "Bachelor of Arts in Development Studies", text: "Bachelor of Arts in Development Studies" },
    { value: "Bachelor of Arts in Economics", text: "Bachelor of Arts in Economics" },
    { value: "Bachelor of Arts in Education", text: "Bachelor of Arts in Education" },
    { value: "Bachelor of Arts in English", text: "Bachelor of Arts in English" },
    { value: "Bachelor of Arts in English Literature", text: "Bachelor of Arts in English Literature" },
    { value: "Bachelor of Arts in Entrepreneurial Management", text: "Bachelor of Arts in Entrepreneurial Management" },
    { value: "Bachelor of Arts in Environment", text: "Bachelor of Arts in Environment" },
    { value: "Bachelor of Arts in European Languages", text: "Bachelor of Arts in European Languages" },
    { value: "Bachelor of Arts in Filipino", text: "Bachelor of Arts in Filipino" },
    { value: "Bachelor of Arts in Film And Audio Visual Communication", text: "Bachelor of Arts in Film And Audio Visual Communication" },
    { value: "Bachelor of Arts in History", text: "Bachelor of Arts in History" },
    { value: "Bachelor of Arts in Humanities", text: "Bachelor of Arts in Humanities" },
    { value: "Bachelor of Arts in International Studies", text: "Bachelor of Arts in International Studies" },
    { value: "Bachelor of Arts in Islamic And Arabic Studies", text: "Bachelor of Arts in Islamic And Arabic Studies" },
    { value: "Bachelor of Arts in Islamic Studies", text: "Bachelor of Arts in Islamic Studies" },
    { value: "Bachelor of Arts in Journalism", text: "Bachelor of Arts in Journalism" },
    { value: "Bachelor of Arts in Language Education", text: "Bachelor of Arts in Language Education" },
    { value: "Bachelor of Arts in Language Teaching", text: "Bachelor of Arts in Language Teaching" },
    { value: "Bachelor of Arts in Legal Management", text: "Bachelor of Arts in Legal Management" },
    { value: "Bachelor of Arts in Letters", text: "Bachelor of Arts in Letters" },
    { value: "Bachelor of Arts in Liberal Arts", text: "Bachelor of Arts in Liberal Arts" },
    { value: "Bachelor of Arts in Linguistics", text: "Bachelor of Arts in Linguistics" },
    { value: "Bachelor of Arts in Literature", text: "Bachelor of Arts in Literature" },
    { value: "Bachelor of Arts in Management", text: "Bachelor of Arts in Management" },
    { value: "Bachelor of Arts in Marketing", text: "Bachelor of Arts in Marketing" },
    { value: "Bachelor of Arts in Mass Communication", text: "Bachelor of Arts in Mass Communication" },
    { value: "Bachelor of Arts in Organizational Communication", text: "Bachelor of Arts in Organizational Communication" },
    { value: "Bachelor of Arts in Philippine Arts", text: "Bachelor of Arts in Philippine Arts" },
    { value: "Bachelor of Arts in Philippine Literature", text: "Bachelor of Arts in Philippine Literature" },
    { value: "Bachelor of Arts in Philippine Studies", text: "Bachelor of Arts in Philippine Studies" },
    { value: "Bachelor of Arts in Philosophy", text: "Bachelor of Arts in Philosophy" },
    { value: "Bachelor of Arts in Political Science", text: "Bachelor of Arts in Political Science" },
    { value: "Bachelor of Arts in Psychology", text: "Bachelor of Arts in Psychology" },
    { value: "Bachelor of Arts in Public Administration", text: "Bachelor of Arts in Public Administration" },
    { value: "Bachelor of Arts in Public Relations", text: "Bachelor of Arts in Public Relations" },
    { value: "Bachelor of Arts in Religion", text: "Bachelor of Arts in Religion" },
    { value: "Bachelor of Arts in Social Sciences", text: "Bachelor of Arts in Social Sciences" },
    { value: "Bachelor of Arts in Social Services", text: "Bachelor of Arts in Social Services" },
    { value: "Bachelor of Arts in Social Work", text: "Bachelor of Arts in Social Work" },
    { value: "Bachelor of Arts in Sociology", text: "Bachelor of Arts in Sociology" },
    { value: "Bachelor of Arts in Spanish", text: "Bachelor of Arts in Spanish" },
    { value: "Bachelor of Arts in Speech And Drama", text: "Bachelor of Arts in Speech And Drama" },
    { value: "Bachelor of Arts in Speech And Theater Arts", text: "Bachelor of Arts in Speech And Theater Arts" },
    { value: "Bachelor of Arts in Speech Communication", text: "Bachelor of Arts in Speech Communication" },
    { value: "Bachelor of Arts in Statistics", text: "Bachelor of Arts in Statistics" },
    { value: "Bachelor of Arts in Theology", text: "Bachelor of Arts in Theology" },
    { value: "Bachelor of Arts in Tourism", text: "Bachelor of Arts in Tourism" },
    { value: "Bachelor of Business And Distributive Arts", text: "Bachelor of Business And Distributive Arts" },
    { value: "Bachelor of Classical Arts", text: "Bachelor of Classical Arts" },
    { value: "Bachelor of Communication Arts", text: "Bachelor of Communication Arts" },
    { value: "Bachelor of Computer Science", text: "Bachelor of Computer Science" },
    { value: "Bachelor of Cooperative Management", text: "Bachelor of Cooperative Management" },
    { value: "Bachelor of Divinity", text: "Bachelor of Divinity" },
    { value: "Bachelor of Education in Human Ecology", text: "Bachelor of Education in Human Ecology" },
    { value: "Bachelor of Elementary Education", text: "Bachelor of Elementary Education" },
    { value: "Bachelor of Science in Engineering", text: "Bachelor of Science in Engineering" },
    { value: "Bachelor of Science in Engineering Technology", text: "Bachelor of Science in Engineering Technology" },
    { value: "Bachelor of Science in English", text: "Bachelor of Science in English" },
    { value: "Bachelor of Science in English Education", text: "Bachelor of Science in English Education" },
    { value: "Bachelor of Science in Entomology", text: "Bachelor of Science in Entomology" },
    { value: "Bachelor of Science in Entrepreneurship", text: "Bachelor of Science in Entrepreneurship" },
    { value: "Bachelor of Science in Environmental Development", text: "Bachelor of Science in Environmental Development" },
    { value: "Bachelor of Science in Environmental Engineering", text: "Bachelor of Science in Environmental Engineering" },
    { value: "Bachelor of Science in Environmental Hygiene", text: "Bachelor of Science in Environmental Hygiene" },
    { value: "Bachelor of Science in Environmental Management", text: "Bachelor of Science in Environmental Management" },
    { value: "Bachelor of Science in Environmental Planning", text: "Bachelor of Science in Environmental Planning" },
    { value: "Bachelor of Science in Environmental Science", text: "Bachelor of Science in Environmental Science" },
    { value: "Bachelor of Science in Evangelical Ministry", text: "Bachelor of Science in Evangelical Ministry" },
    { value: "Bachelor of Science in Experimental Statistics", text: "Bachelor of Science in Experimental Statistics" },
    { value: "Bachelor of Science in Extension Education", text: "Bachelor of Science in Extension Education" },
    { value: "Bachelor of Science in Family And Child Development", text: "Bachelor of Science in Family And Child Development" },
    { value: "Bachelor of Science in Finance", text: "Bachelor of Science in Finance" },
    { value: "Bachelor of Science in Food Technology", text: "Bachelor of Science in Food Technology" },
    { value: "Bachelor of Science in Forestry", text: "Bachelor of Science in Forestry" },
    { value: "Bachelor of Science in Geography", text: "Bachelor of Science in Geography" },
    { value: "Bachelor of Science in Geology", text: "Bachelor of Science in Geology" },
    { value: "Bachelor of Science in Health And Physical Education", text: "Bachelor of Science in Health And Physical Education" },
    { value: "Bachelor of Science in Health Science", text: "Bachelor of Science in Health Science" },
    { value: "Bachelor of Science in Hospitality Management", text: "Bachelor of Science in Hospitality Management" },
    { value: "Bachelor of Science in Human Resource Management", text: "Bachelor of Science in Human Resource Management" },
    { value: "Bachelor of Science in Information Technology", text: "Bachelor of Science in Information Technology" },
    { value: "Bachelor of Science in International Business", text: "Bachelor of Science in International Business" },
    { value: "Bachelor of Science in International Studies", text: "Bachelor of Science in International Studies" },
    { value: "Bachelor of Science in Marine Biology", text: "Bachelor of Science in Marine Biology" },
    { value: "Bachelor of Science in Marketing", text: "Bachelor of Science in Marketing" },
    { value: "Bachelor of Science in Mathematics", text: "Bachelor of Science in Mathematics" },
    { value: "Bachelor of Science in Mechanical Engineering", text: "Bachelor of Science in Mechanical Engineering" },
    { value: "Bachelor of Science in Mechanical Technology", text: "Bachelor of Science in Mechanical Technology" },
    { value: "Bachelor of Science in Medical Technology", text: "Bachelor of Science in Medical Technology" },
    { value: "Bachelor of Science in Metallurgical Engineering", text: "Bachelor of Science in Metallurgical Engineering" },
    { value: "Bachelor of Science in Metallurgy", text: "Bachelor of Science in Metallurgy" },
    { value: "Bachelor of Science in Meteorology", text: "Bachelor of Science in Meteorology" },
    { value: "Bachelor of Science in Microbiology", text: "Bachelor of Science in Microbiology" },
    { value: "Bachelor of Science in Mining Engineering", text: "Bachelor of Science in Mining Engineering" },
    { value: "Bachelor of Science in Molecular Biology And Biotechnology", text: "Bachelor of Science in Molecular Biology And Biotechnology" },
    { value: "Bachelor of Science in Music", text: "Bachelor of Science in Music" },
    { value: "Bachelor of Science in Music Education", text: "Bachelor of Science in Music Education" },
    { value: "Bachelor of Science in Natural Science", text: "Bachelor of Science in Natural Science" },
    { value: "Bachelor of Science in Nautical Science", text: "Bachelor of Science in Nautical Science" },
    { value: "Bachelor of Science in Naval Architecture And Marine Engineering", text: "Bachelor of Science in Naval Architecture And Marine Engineering" },
    { value: "Bachelor of Science in Nursing", text: "Bachelor of Science in Nursing" },
    { value: "Bachelor of Science in Nursing (Supplemental)", text: "Bachelor of Science in Nursing (Supplemental)" },
    { value: "Bachelor of Science in Nursing Education", text: "Bachelor of Science in Nursing Education" },
    { value: "Bachelor of Science in Nutrition", text: "Bachelor of Science in Nutrition" },
    { value: "Bachelor of Science in Nutrition And Dietetics", text: "Bachelor of Science in Nutrition And Dietetics" },
    { value: "Bachelor of Science in Nutrition And Dietetics For Teachers", text: "Bachelor of Science in Nutrition And Dietetics For Teachers" },
    { value: "Bachelor of Science in Occupational Therapy", text: "Bachelor of Science in Occupational Therapy" },
    { value: "Bachelor of Science in Oceanography", text: "Bachelor of Science in Oceanography" },
    { value: "Bachelor of Science in Office Administration", text: "Bachelor of Science in Office Administration" },
    { value: "Bachelor of Science in Office Administration /Technology", text: "Bachelor of Science in Office Administration /Technology" },
    { value: "Bachelor of Science in Office Management", text: "Bachelor of Science in Office Management" },
    { value: "Bachelor of Science in Paramedics", text: "Bachelor of Science in Paramedics" },
    { value: "Bachelor of Science in Peace And Security Studies", text: "Bachelor of Science in Peace And Security Studies" },
    { value: "Bachelor of Science in Pedagogy", text: "Bachelor of Science in Pedagogy" },
    { value: "Bachelor of Science in Petroleum Engineering", text: "Bachelor of Science in Petroleum Engineering" },
    { value: "Bachelor of Science in Pharmaceutical Chemistry", text: "Bachelor of Science in Pharmaceutical Chemistry" },
    { value: "Bachelor of Science in Pharmacology", text: "Bachelor of Science in Pharmacology" },
    { value: "Bachelor of Science in Pharmacy", text: "Bachelor of Science in Pharmacy" },
    { value: "Bachelor of Science in Physical Education", text: "Bachelor of Science in Physical Education" },
    { value: "Bachelor of Science in Physical Therapy", text: "Bachelor of Science in Physical Therapy" },
    { value: "Bachelor of Science in Physics", text: "Bachelor of Science in Physics" },
    { value: "Bachelor of Science in Physics For Teachers", text: "Bachelor of Science in Physics For Teachers" },
    { value: "Bachelor of Science in Physics Teaching", text: "Bachelor of Science in Physics Teaching" },
    { value: "Bachelor of Science in Physics-Mathematics", text: "Bachelor of Science in Physics-Mathematics" },
    { value: "Bachelor of Science in Physiology", text: "Bachelor of Science in Physiology" },
    { value: "Bachelor of Science in Pilipino", text: "Bachelor of Science in Pilipino" },
    { value: "Bachelor of Science in Plant Science", text: "Bachelor of Science in Plant Science" },
    { value: "Bachelor of Science in Plumbing Engineering", text: "Bachelor of Science in Plumbing Engineering" },
    { value: "Bachelor of Science in Police Administration", text: "Bachelor of Science in Police Administration" },
    { value: "Bachelor of Science in Political Economy", text: "Bachelor of Science in Political Economy" },
    { value: "Bachelor of Science in Postal Administration", text: "Bachelor of Science in Postal Administration" },
    { value: "Bachelor of Science in Practical Arts", text: "Bachelor of Science in Practical Arts" },
    { value: "Bachelor of Science in Practical Arts Education", text: "Bachelor of Science in Practical Arts Education" },
    { value: "Bachelor of Science in Pre-Medicine", text: "Bachelor of Science in Pre-Medicine" },
    { value: "Bachelor of Science in Psychology", text: "Bachelor of Science in Psychology" },
    { value: "Bachelor of Science in Public Administration", text: "Bachelor of Science in Public Administration" },
    { value: "Bachelor of Science in Public Health", text: "Bachelor of Science in Public Health" },
    { value: "Bachelor of Science in Radio And Electronics Engineering", text: "Bachelor of Science in Radio And Electronics Engineering" },
    { value: "Bachelor of Science in Radio Communication Technology", text: "Bachelor of Science in Radio Communication Technology" },
    { value: "Bachelor of Science in Radiologic Technology", text: "Bachelor of Science in Radiologic Technology" },
    { value: "Bachelor of Science in Real Estate", text: "Bachelor of Science in Real Estate" },
    { value: "Bachelor of Science in Recreation And Parks Administration", text: "Bachelor of Science in Recreation And Parks Administration" },
    { value: "Bachelor of Science in Recreation Management", text: "Bachelor of Science in Recreation Management" },
    { value: "Bachelor of Science in Religious Education", text: "Bachelor of Science in Religious Education" },
    { value: "Bachelor of Science in Respiratory Therapy", text: "Bachelor of Science in Respiratory Therapy" },
    { value: "Bachelor of Science in Rice Technology", text: "Bachelor of Science in Rice Technology" },
    { value: "Bachelor of Science in Rural Development Management", text: "Bachelor of Science in Rural Development Management" },
    { value: "Bachelor of Science in Rural Medicine", text: "Bachelor of Science in Rural Medicine" },
    { value: "Bachelor of Science in Sanitary Engineering", text: "Bachelor of Science in Sanitary Engineering" },
    { value: "Bachelor of Science in Sanitary Science", text: "Bachelor of Science in Sanitary Science" },
    { value: "Bachelor of Science in Secondary Education", text: "Bachelor of Science in Secondary Education" },
    { value: "Bachelor of Science in Secretarial Administration", text: "Bachelor of Science in Secretarial Administration" },
    { value: "Bachelor of Science in Secretarial Education", text: "Bachelor of Science in Secretarial Education" },
    { value: "Bachelor of Science in Secretarial Management", text: "Bachelor of Science in Secretarial Management" },
    { value: "Bachelor of Science in Secretarial Science", text: "Bachelor of Science in Secretarial Science" },
    { value: "Bachelor of Science in Shipping Management And Accountancy", text: "Bachelor of Science in Shipping Management And Accountancy" },
    { value: "Bachelor of Science in Social Services", text: "Bachelor of Science in Social Services" },
    { value: "Bachelor of Science in Social Work", text: "Bachelor of Science in Social Work" },
    { value: "Bachelor of Science in Sociology", text: "Bachelor of Science in Sociology" },
    { value: "Bachelor of Science in Software Technology", text: "Bachelor of Science in Software Technology" },
    { value: "Bachelor of Science in Soils", text: "Bachelor of Science in Soils" },
    { value: "Bachelor of Science in Speech and Drama", text: "Bachelor of Science in Speech and Drama" },
    { value: "Bachelor of Science in Speech Pathology", text: "Bachelor of Science in Speech Pathology" },
    { value: "Bachelor of Science in Statistics", text: "Bachelor of Science in Statistics" },
    { value: "Bachelor of Science in Sugar Technology", text: "Bachelor of Science in Sugar Technology" },
    { value: "Bachelor of Science in Supply Administration", text: "Bachelor of Science in Supply Administration" },
    { value: "Bachelor of Science in Supply Management", text: "Bachelor of Science in Supply Management" },
    { value: "Bachelor of Science in Teaching", text: "Bachelor of Science in Teaching" },
    { value: "Bachelor of Science in Teaching Arabic", text: "Bachelor of Science in Teaching Arabic" },
    { value: "Bachelor of Science in Technical Education", text: "Bachelor of Science in Technical Education" },
    { value: "Bachelor of Science in Technician Teacher Education", text: "Bachelor of Science in Technician Teacher Education" },
    { value: "Bachelor of Science in Technological Education", text: "Bachelor of Science in Technological Education" },
    { value: "Bachelor of Science in Textile Engineering", text: "Bachelor of Science in Textile Engineering" },
    { value: "Bachelor of Science in Theater Arts", text: "Bachelor of Science in Theater Arts" },
    { value: "Bachelor of Science in Theology", text: "Bachelor of Science in Theology" },
    { value: "Bachelor of Science in Tourism", text: "Bachelor of Science in Tourism" },
    { value: "Bachelor of Science in Tourism and Hotel Restaurant Management", text: "Bachelor of Science in Tourism and Hotel Restaurant Management" },
    { value: "Bachelor of Science in Tourism and Travel Management", text: "Bachelor of Science in Tourism and Travel Management" },
    { value: "Bachelor of Science in Town and Country Planning", text: "Bachelor of Science in Town and Country Planning" },
    { value: "Bachelor of Science in Trade Technology", text: "Bachelor of Science in Trade Technology" },
    { value: "Bachelor of Science in Upland Agricultural Entrepreneurship", text: "Bachelor of Science in Upland Agricultural Entrepreneurship" },
    { value: "Bachelor of Science in Veterinary Technology", text: "Bachelor of Science in Veterinary Technology" },
    { value: "Bachelor of Science in Volcanology", text: "Bachelor of Science in Volcanology" },
    { value: "Bachelor of Science in Zoology", text: "Bachelor of Science in Zoology" },
    { value: "Bachelor of Science Library", text: "Bachelor of Science Library" },
    { value: "Bachelor of Science Management Information System", text: "Bachelor of Science Management Information System" },
    { value: "Bachelor of Science Marine Technology", text: "Bachelor of Science Marine Technology" },
    { value: "Bachelor of Science Naval Architecture", text: "Bachelor of Science Naval Architecture" },
    { value: "Bachelor of Science Nursing and Community Health", text: "Bachelor of Science Nursing and Community Health" },
    { value: "Bachelor of Science Postal Management", text: "Bachelor of Science Postal Management" },
    { value: "Bachelor of Science Textile Garment Technology", text: "Bachelor of Science Textile Garment Technology" },
    { value: "Bachelor of Secondary Education", text: "Bachelor of Secondary Education" },
    { value: "Bachelor of Secondary Education Major in Physical Education", text: "Bachelor of Secondary Education Major in Physical Education" },
    { value: "Bachelor of Special Education", text: "Bachelor of Special Education" },
    { value: "Bachelor of Sports Science", text: "Bachelor of Sports Science" },
    { value: "Bachelor of Teaching Home Economics and Livehood Education", text: "Bachelor of Teaching Home Economics and Livehood Education" },
    { value: "Bachelor of Teaching Technology and Home Economics", text: "Bachelor of Teaching Technology and Home Economics" },
    { value: "Bachelor of Technical Teacher & Education", text: "Bachelor of Technical Teacher & Education" },
    { value: "Bachelor of Technology", text: "Bachelor of Technology" },
    { value: "Bachelor of Technology in Environmental Management", text: "Bachelor of Technology in Environmental Management" },
    { value: "Bachelor of Technology in Horticulture Management", text: "Bachelor of Technology in Horticulture Management" },
    { value: "Bachelor of Theology", text: "Bachelor of Theology" },
    { value: "Doctor in Biology", text: "Doctor in Biology" },
    { value: "Doctor in Business Management", text: "Doctor in Business Management" },
    { value: "Doctor in Development Administration", text: "Doctor in Development Administration" },
    { value: "Doctor in Education", text: "Doctor in Education" },
    { value: "Doctor in Educational Management/Administration", text: "Doctor in Educational Management/Administration" },
    { value: "Doctor in English", text: "Doctor in English" },
    { value: "Doctor in Management", text: "Doctor in Management" },
    { value: "Doctor in Plant Pathology", text: "Doctor in Plant Pathology" },
    { value: "Doctor in Psychology", text: "Doctor in Psychology" },
    { value: "Doctor in Technological Education", text: "Doctor in Technological Education" },
    { value: "Doctor in/of Public Administration", text: "Doctor in/of Public Administration" },
    { value: "Doctor of Agricultural Chemistry", text: "Doctor of Agricultural Chemistry" },
    { value: "Doctor of Agricultural Education", text: "Doctor of Agricultural Education" },
    { value: "Doctor of Agricultural Engineering", text: "Doctor of Agricultural Engineering" },
    { value: "Doctor of Agricultural Extension", text: "Doctor of Agricultural Extension" },
    { value: "Doctor of Arts", text: "Doctor of Arts" },
    { value: "Doctor of Arts in Language and Literature", text: "Doctor of Arts in Language and Literature" },
    { value: "Doctor of Business Administration", text: "Doctor of Business Administration" },
    { value: "Doctor of Business Technology", text: "Doctor of Business Technology" },
    { value: "Doctor of Civil Laws", text: "Doctor of Civil Laws" },
    { value: "Doctor of Dental Medicine", text: "Doctor of Dental Medicine" },
    { value: "Doctor of Education", text: "Doctor of Education" },
    { value: "Doctor of Education in Educational Administration", text: "Doctor of Education in Educational Administration" },
    { value: "Doctor of Education in Educational Management", text: "Doctor of Education in Educational Management" },
    { value: "Doctor of Education in Industrial Education Management", text: "Doctor of Education in Industrial Education Management" },
    { value: "Doctor of Letters", text: "Doctor of Letters" },
    { value: "Doctor of Mathematics Education", text: "Doctor of Mathematics Education" },
    { value: "Doctor of Medicine", text: "Doctor of Medicine" }
  ];