export const coursesAndPrograms = [
    { value: "Bachelor In Accountancy", text: "Bachelor In Accountancy" },
    { value: "Bachelor In Advertising", text: "Bachelor In Advertising" },
    { value: "Bachelor In Advertising And Public Relation", text: "Bachelor In Advertising And Public Relation" },
    { value: "Bachelor In Agro-Forestry Technology", text: "Bachelor In Agro-Forestry Technology" },
    { value: "Bachelor In Applied Deaf Studies", text: "Bachelor In Applied Deaf Studies" },
    { value: "Bachelor In Applied Economics", text: "Bachelor In Applied Economics" },
    { value: "Bachelor In Applied Science", text: "Bachelor In Applied Science" },
    { value: "Bachelor In Banking And Finance", text: "Bachelor In Banking And Finance" },
    { value: "Bachelor In Broadcast Communications", text: "Bachelor In Broadcast Communications" },
    { value: "Bachelor In Business Administration", text: "Bachelor In Business Administration" },
    { value: "Bachelor In Business Engineering", text: "Bachelor In Business Engineering" },
    { value: "Bachelor In Business Journalism", text: "Bachelor In Business Journalism" },
    { value: "Bachelor In Business Management", text: "Bachelor In Business Management" },
    { value: "Bachelor In Business Teacher Education", text: "Bachelor In Business Teacher Education" },
    { value: "Bachelor In Commercial Science", text: "Bachelor In Commercial Science" },
    { value: "Bachelor In Computer Data Processing Management", text: "Bachelor In Computer Data Processing Management" },
    { value: "Bachelor In Computer Management", text: "Bachelor In Computer Management" },
    { value: "Bachelor In Computer Technology", text: "Bachelor In Computer Technology" },
    { value: "Bachelor In Cooperative", text: "Bachelor In Cooperative" },
    { value: "Bachelor In Entrepreneurial Management", text: "Bachelor In Entrepreneurial Management" },
    { value: "Bachelor In Human Behavior Technology", text: "Bachelor In Human Behavior Technology" },
    { value: "Bachelor In Industrial Psychology", text: "Bachelor In Industrial Psychology" },
    { value: "Bachelor In Industrial Technology", text: "Bachelor In Industrial Technology" },
    { value: "Bachelor In Information Technology", text: "Bachelor In Information Technology" },
    { value: "Bachelor In Inter-Disciplinary Studies", text: "Bachelor In Inter-Disciplinary Studies" },
    { value: "Bachelor In Journalism", text: "Bachelor In Journalism" },
    { value: "Bachelor In Library And Information Science", text: "Bachelor In Library And Information Science" },
    { value: "Bachelor In Office Administration", text: "Bachelor In Office Administration" },
    { value: "Bachelor In Performing Arts", text: "Bachelor In Performing Arts" },
    { value: "Bachelor In Physical Education", text: "Bachelor In Physical Education" },
    { value: "Bachelor In Pilipino", text: "Bachelor In Pilipino" },
    { value: "Bachelor In Political Economy", text: "Bachelor In Political Economy" },
    { value: "Bachelor In Tourism", text: "Bachelor In Tourism" },
    { value: "Bachelor In Transportation Management", text: "Bachelor In Transportation Management" },
    { value: "Bachelor Of Agricultural Entrepreneurship", text: "Bachelor Of Agricultural Entrepreneurship" },
    { value: "Bachelor Of Agricultural Technology", text: "Bachelor Of Agricultural Technology" },
    { value: "Bachelor Of Arts", text: "Bachelor Of Arts" },
    { value: "Bachelor Of Arts In Anthropology", text: "Bachelor Of Arts In Anthropology" },
    { value: "Bachelor Of Arts In Applied Psychology", text: "Bachelor Of Arts In Applied Psychology" },
    { value: "Bachelor Of Arts In Applied Sociology", text: "Bachelor Of Arts In Applied Sociology" },
    { value: "Bachelor Of Arts In Asian Studies", text: "Bachelor Of Arts In Asian Studies" },
    { value: "Bachelor Of Arts In Basic Medical Science", text: "Bachelor Of Arts In Basic Medical Science" },
    { value: "Bachelor Of Arts In Behavioral Science", text: "Bachelor Of Arts In Behavioral Science" },
    { value: "Bachelor Of Arts In Broadcast Communication", text: "Bachelor Of Arts In Broadcast Communication" },
    { value: "Bachelor Of Arts In College Teaching", text: "Bachelor Of Arts In College Teaching" },
    { value: "Bachelor Of Arts In Commerce", text: "Bachelor Of Arts In Commerce" },
    { value: "Bachelor Of Arts In Communication", text: "Bachelor Of Arts In Communication" },
    { value: "Bachelor Of Arts In Communication Arts", text: "Bachelor Of Arts In Communication Arts" },
    { value: "Bachelor Of Arts In Comparative Literature", text: "Bachelor Of Arts In Comparative Literature" },
    { value: "Bachelor Of Arts In Computer Science", text: "Bachelor Of Arts In Computer Science" },
    { value: "Bachelor Of Arts In Computer Teaching", text: "Bachelor Of Arts In Computer Teaching" },
    { value: "Bachelor Of Arts In Development Studies", text: "Bachelor Of Arts In Development Studies" },
    { value: "Bachelor Of Arts In Economics", text: "Bachelor Of Arts In Economics" },
    { value: "Bachelor Of Arts In Education", text: "Bachelor Of Arts In Education" },
    { value: "Bachelor Of Arts In English", text: "Bachelor Of Arts In English" },
    { value: "Bachelor Of Arts In English Literature", text: "Bachelor Of Arts In English Literature" },
    { value: "Bachelor Of Arts In Entrepreneurial Management", text: "Bachelor Of Arts In Entrepreneurial Management" },
    { value: "Bachelor Of Arts In Environment", text: "Bachelor Of Arts In Environment" },
    { value: "Bachelor Of Arts In European Languages", text: "Bachelor Of Arts In European Languages" },
    { value: "Bachelor Of Arts In Filipino", text: "Bachelor Of Arts In Filipino" },
    { value: "Bachelor Of Arts In Film And Audio Visual Communication", text: "Bachelor Of Arts In Film And Audio Visual Communication" },
    { value: "Bachelor Of Arts In History", text: "Bachelor Of Arts In History" },
    { value: "Bachelor Of Arts In Humanities", text: "Bachelor Of Arts In Humanities" },
    { value: "Bachelor Of Arts In International Studies", text: "Bachelor Of Arts In International Studies" },
    { value: "Bachelor Of Arts In Islamic And Arabic Studies", text: "Bachelor Of Arts In Islamic And Arabic Studies" },
    { value: "Bachelor Of Arts In Islamic Studies", text: "Bachelor Of Arts In Islamic Studies" },
    { value: "Bachelor Of Arts In Journalism", text: "Bachelor Of Arts In Journalism" },
    { value: "Bachelor Of Arts In Language Education", text: "Bachelor Of Arts In Language Education" },
    { value: "Bachelor Of Arts In Language Teaching", text: "Bachelor Of Arts In Language Teaching" },
    { value: "Bachelor Of Arts In Legal Management", text: "Bachelor Of Arts In Legal Management" },
    { value: "Bachelor Of Arts In Letters", text: "Bachelor Of Arts In Letters" },
    { value: "Bachelor Of Arts In Liberal Arts", text: "Bachelor Of Arts In Liberal Arts" },
    { value: "Bachelor Of Arts In Linguistics", text: "Bachelor Of Arts In Linguistics" },
    { value: "Bachelor Of Arts In Literature", text: "Bachelor Of Arts In Literature" },
    { value: "Bachelor Of Arts In Management", text: "Bachelor Of Arts In Management" },
    { value: "Bachelor Of Arts In Marketing", text: "Bachelor Of Arts In Marketing" },
    { value: "Bachelor Of Arts In Mass Communication", text: "Bachelor Of Arts In Mass Communication" },
    { value: "Bachelor Of Arts In Organizational Communication", text: "Bachelor Of Arts In Organizational Communication" },
    { value: "Bachelor Of Arts In Philippine Arts", text: "Bachelor Of Arts In Philippine Arts" },
    { value: "Bachelor Of Arts In Philippine Literature", text: "Bachelor Of Arts In Philippine Literature" },
    { value: "Bachelor Of Arts In Philippine Studies", text: "Bachelor Of Arts In Philippine Studies" },
    { value: "Bachelor Of Arts In Philosophy", text: "Bachelor Of Arts In Philosophy" },
    { value: "Bachelor Of Arts In Political Science", text: "Bachelor Of Arts In Political Science" },
    { value: "Bachelor Of Arts In Psychology", text: "Bachelor Of Arts In Psychology" },
    { value: "Bachelor Of Arts In Public Administration", text: "Bachelor Of Arts In Public Administration" },
    { value: "Bachelor Of Arts In Public Relations", text: "Bachelor Of Arts In Public Relations" },
    { value: "Bachelor Of Arts In Religion", text: "Bachelor Of Arts In Religion" },
    { value: "Bachelor Of Arts In Social Sciences", text: "Bachelor Of Arts In Social Sciences" },
    { value: "Bachelor Of Arts In Social Services", text: "Bachelor Of Arts In Social Services" },
    { value: "Bachelor Of Arts In Social Work", text: "Bachelor Of Arts In Social Work" },
    { value: "Bachelor Of Arts In Sociology", text: "Bachelor Of Arts In Sociology" },
    { value: "Bachelor Of Arts In Spanish", text: "Bachelor Of Arts In Spanish" },
    { value: "Bachelor Of Arts In Speech And Drama", text: "Bachelor Of Arts In Speech And Drama" },
    { value: "Bachelor Of Arts In Speech And Theater Arts", text: "Bachelor Of Arts In Speech And Theater Arts" },
    { value: "Bachelor Of Arts In Speech Communication", text: "Bachelor Of Arts In Speech Communication" },
    { value: "Bachelor Of Arts In Statistics", text: "Bachelor Of Arts In Statistics" },
    { value: "Bachelor Of Arts In Theology", text: "Bachelor Of Arts In Theology" },
    { value: "Bachelor Of Arts In Tourism", text: "Bachelor Of Arts In Tourism" },
    { value: "Bachelor Of Business And Distributive Arts", text: "Bachelor Of Business And Distributive Arts" },
    { value: "Bachelor Of Classical Arts", text: "Bachelor Of Classical Arts" },
    { value: "Bachelor Of Communication Arts", text: "Bachelor Of Communication Arts" },
    { value: "Bachelor Of Computer Science", text: "Bachelor Of Computer Science" },
    { value: "Bachelor Of Cooperative Management", text: "Bachelor Of Cooperative Management" },
    { value: "Bachelor Of Divinity", text: "Bachelor Of Divinity" },
    { value: "Bachelor Of Education In Human Ecology", text: "Bachelor Of Education In Human Ecology" },
    { value: "Bachelor Of Elementary Education", text: "Bachelor Of Elementary Education" },
    { value: "Bachelor Of Science In Engineering", text: "Bachelor Of Science In Engineering" },
    { value: "Bachelor Of Science In Engineering Technology", text: "Bachelor Of Science In Engineering Technology" },
    { value: "Bachelor Of Science In English", text: "Bachelor Of Science In English" },
    { value: "Bachelor Of Science In English Education", text: "Bachelor Of Science In English Education" },
    { value: "Bachelor Of Science In Entomology", text: "Bachelor Of Science In Entomology" },
    { value: "Bachelor Of Science In Entrepreneurship", text: "Bachelor Of Science In Entrepreneurship" },
    { value: "Bachelor Of Science In Environmental Development", text: "Bachelor Of Science In Environmental Development" },
    { value: "Bachelor Of Science In Environmental Engineering", text: "Bachelor Of Science In Environmental Engineering" },
    { value: "Bachelor Of Science In Environmental Hygiene", text: "Bachelor Of Science In Environmental Hygiene" },
    { value: "Bachelor Of Science In Environmental Management", text: "Bachelor Of Science In Environmental Management" },
    { value: "Bachelor Of Science In Environmental Planning", text: "Bachelor Of Science In Environmental Planning" },
    { value: "Bachelor Of Science In Environmental Science", text: "Bachelor Of Science In Environmental Science" },
    { value: "Bachelor Of Science In Evangelical Ministry", text: "Bachelor Of Science In Evangelical Ministry" },
    { value: "Bachelor Of Science In Experimental Statistics", text: "Bachelor Of Science In Experimental Statistics" },
    { value: "Bachelor Of Science In Extension Education", text: "Bachelor Of Science In Extension Education" },
    { value: "Bachelor Of Science In Family And Child Development", text: "Bachelor Of Science In Family And Child Development" },
    { value: "Bachelor Of Science In Finance", text: "Bachelor Of Science In Finance" },
    { value: "Bachelor Of Science In Food Technology", text: "Bachelor Of Science In Food Technology" },
    { value: "Bachelor Of Science In Forestry", text: "Bachelor Of Science In Forestry" },
    { value: "Bachelor Of Science In Geography", text: "Bachelor Of Science In Geography" },
    { value: "Bachelor Of Science In Geology", text: "Bachelor Of Science In Geology" },
    { value: "Bachelor Of Science In Health And Physical Education", text: "Bachelor Of Science In Health And Physical Education" },
    { value: "Bachelor Of Science In Health Science", text: "Bachelor Of Science In Health Science" },
    { value: "Bachelor Of Science In Hospitality Management", text: "Bachelor Of Science In Hospitality Management" },
    { value: "Bachelor Of Science In Human Resource Management", text: "Bachelor Of Science In Human Resource Management" },
    { value: "Bachelor Of Science In Information Technology", text: "Bachelor Of Science In Information Technology" },
    { value: "Bachelor Of Science In International Business", text: "Bachelor Of Science In International Business" },
    { value: "Bachelor Of Science In International Studies", text: "Bachelor Of Science In International Studies" },
    { value: "Bachelor Of Science In Marine Biology", text: "Bachelor Of Science In Marine Biology" },
    { value: "Bachelor Of Science In Marketing", text: "Bachelor Of Science In Marketing" },
    { value: "Bachelor Of Science In Mathematics", text: "Bachelor Of Science In Mathematics" },
    { value: "Bachelor Of Science In Mechanical Engineering", text: "Bachelor Of Science In Mechanical Engineering" },
    { value: "Bachelor Of Science In Mechanical Technology", text: "Bachelor Of Science In Mechanical Technology" },
    { value: "Bachelor Of Science In Medical Technology", text: "Bachelor Of Science In Medical Technology" },
    { value: "Bachelor Of Science In Metallurgical Engineering", text: "Bachelor Of Science In Metallurgical Engineering" },
    { value: "Bachelor Of Science In Metallurgy", text: "Bachelor Of Science In Metallurgy" },
    { value: "Bachelor Of Science In Meteorology", text: "Bachelor Of Science In Meteorology" },
    { value: "Bachelor Of Science In Microbiology", text: "Bachelor Of Science In Microbiology" },
    { value: "Bachelor Of Science In Mining Engineering", text: "Bachelor Of Science In Mining Engineering" },
    { value: "Bachelor Of Science In Molecular Biology And Biotechnology", text: "Bachelor Of Science In Molecular Biology And Biotechnology" },
    { value: "Bachelor Of Science In Music", text: "Bachelor Of Science In Music" },
    { value: "Bachelor Of Science In Music Education", text: "Bachelor Of Science In Music Education" },
    { value: "Bachelor Of Science In Natural Science", text: "Bachelor Of Science In Natural Science" },
    { value: "Bachelor Of Science In Nautical Science", text: "Bachelor Of Science In Nautical Science" },
    { value: "Bachelor Of Science In Naval Architecture And Marine Engineering", text: "Bachelor Of Science In Naval Architecture And Marine Engineering" },
    { value: "Bachelor Of Science In Nursing", text: "Bachelor Of Science In Nursing" },
    { value: "Bachelor Of Science In Nursing (Supplemental)", text: "Bachelor Of Science In Nursing (Supplemental)" },
    { value: "Bachelor Of Science In Nursing Education", text: "Bachelor Of Science In Nursing Education" },
    { value: "Bachelor Of Science In Nutrition", text: "Bachelor Of Science In Nutrition" },
    { value: "Bachelor Of Science In Nutrition And Dietetics", text: "Bachelor Of Science In Nutrition And Dietetics" },
    { value: "Bachelor Of Science In Nutrition And Dietetics For Teachers", text: "Bachelor Of Science In Nutrition And Dietetics For Teachers" },
    { value: "Bachelor Of Science In Occupational Therapy", text: "Bachelor Of Science In Occupational Therapy" },
    { value: "Bachelor Of Science In Oceanography", text: "Bachelor Of Science In Oceanography" },
    { value: "Bachelor Of Science In Office Administration", text: "Bachelor Of Science In Office Administration" },
    { value: "Bachelor Of Science In Office Administration /Technology", text: "Bachelor Of Science In Office Administration /Technology" },
    { value: "Bachelor Of Science In Office Management", text: "Bachelor Of Science In Office Management" },
    { value: "Bachelor Of Science In Paramedics", text: "Bachelor Of Science In Paramedics" },
    { value: "Bachelor Of Science In Peace And Security Studies", text: "Bachelor Of Science In Peace And Security Studies" },
    { value: "Bachelor Of Science In Pedagogy", text: "Bachelor Of Science In Pedagogy" },
    { value: "Bachelor Of Science In Petroleum Engineering", text: "Bachelor Of Science In Petroleum Engineering" },
    { value: "Bachelor Of Science In Pharmaceutical Chemistry", text: "Bachelor Of Science In Pharmaceutical Chemistry" },
    { value: "Bachelor Of Science In Pharmacology", text: "Bachelor Of Science In Pharmacology" },
    { value: "Bachelor Of Science In Pharmacy", text: "Bachelor Of Science In Pharmacy" },
    { value: "Bachelor Of Science In Physical Education", text: "Bachelor Of Science In Physical Education" },
    { value: "Bachelor Of Science In Physical Therapy", text: "Bachelor Of Science In Physical Therapy" },
    { value: "Bachelor Of Science In Physics", text: "Bachelor Of Science In Physics" },
    { value: "Bachelor Of Science In Physics For Teachers", text: "Bachelor Of Science In Physics For Teachers" },
    { value: "Bachelor Of Science In Physics Teaching", text: "Bachelor Of Science In Physics Teaching" },
    { value: "Bachelor Of Science In Physics-Mathematics", text: "Bachelor Of Science In Physics-Mathematics" },
    { value: "Bachelor Of Science In Physiology", text: "Bachelor Of Science In Physiology" },
    { value: "Bachelor Of Science In Pilipino", text: "Bachelor Of Science In Pilipino" },
    { value: "Bachelor Of Science In Plant Science", text: "Bachelor Of Science In Plant Science" },
    { value: "Bachelor Of Science In Plumbing Engineering", text: "Bachelor Of Science In Plumbing Engineering" },
    { value: "Bachelor Of Science In Police Administration", text: "Bachelor Of Science In Police Administration" },
    { value: "Bachelor Of Science In Political Economy", text: "Bachelor Of Science In Political Economy" },
    { value: "Bachelor Of Science In Postal Administration", text: "Bachelor Of Science In Postal Administration" },
    { value: "Bachelor Of Science In Practical Arts", text: "Bachelor Of Science In Practical Arts" },
    { value: "Bachelor Of Science In Practical Arts Education", text: "Bachelor Of Science In Practical Arts Education" },
    { value: "Bachelor Of Science In Pre-Medicine", text: "Bachelor Of Science In Pre-Medicine" },
    { value: "Bachelor Of Science In Psychology", text: "Bachelor Of Science In Psychology" },
    { value: "Bachelor Of Science In Public Administration", text: "Bachelor Of Science In Public Administration" },
    { value: "Bachelor Of Science In Public Health", text: "Bachelor Of Science In Public Health" },
    { value: "Bachelor Of Science In Radio And Electronics Engineering", text: "Bachelor Of Science In Radio And Electronics Engineering" },
    { value: "Bachelor Of Science In Radio Communication Technology", text: "Bachelor Of Science In Radio Communication Technology" },
    { value: "Bachelor Of Science In Radiologic Technology", text: "Bachelor Of Science In Radiologic Technology" },
    { value: "Bachelor Of Science In Real Estate", text: "Bachelor Of Science In Real Estate" },
    { value: "Bachelor Of Science In Recreation And Parks Administration", text: "Bachelor Of Science In Recreation And Parks Administration" },
    { value: "Bachelor Of Science In Recreation Management", text: "Bachelor Of Science In Recreation Management" },
    { value: "Bachelor Of Science In Religious Education", text: "Bachelor Of Science In Religious Education" },
    { value: "Bachelor Of Science In Respiratory Therapy", text: "Bachelor Of Science In Respiratory Therapy" },
    { value: "Bachelor Of Science In Rice Technology", text: "Bachelor Of Science In Rice Technology" },
    { value: "Bachelor Of Science In Rural Development Management", text: "Bachelor Of Science In Rural Development Management" },
    { value: "Bachelor Of Science In Rural Medicine", text: "Bachelor Of Science In Rural Medicine" },
    { value: "Bachelor Of Science In Sanitary Engineering", text: "Bachelor Of Science In Sanitary Engineering" },
    { value: "Bachelor Of Science In Sanitary Science", text: "Bachelor Of Science In Sanitary Science" },
    { value: "Bachelor Of Science In Secondary Education", text: "Bachelor Of Science In Secondary Education" },
    { value: "Bachelor Of Science In Secretarial Administration", text: "Bachelor Of Science In Secretarial Administration" },
    { value: "Bachelor Of Science In Secretarial Education", text: "Bachelor Of Science In Secretarial Education" },
    { value: "Bachelor Of Science In Secretarial Management", text: "Bachelor Of Science In Secretarial Management" },
    { value: "Bachelor Of Science In Secretarial Science", text: "Bachelor Of Science In Secretarial Science" },
    { value: "Bachelor Of Science In Shipping Management And Accountancy", text: "Bachelor Of Science In Shipping Management And Accountancy" },
    { value: "Bachelor Of Science In Social Services", text: "Bachelor Of Science In Social Services" },
    { value: "Bachelor of Science in Social Work", text: "Bachelor of Science in Social Work" },
    { value: "Bachelor of Science in Sociology", text: "Bachelor of Science in Sociology" },
    { value: "Bachelor of Science in Software Technology", text: "Bachelor of Science in Software Technology" },
    { value: "Bachelor of Science in Soils", text: "Bachelor of Science in Soils" },
    { value: "Bachelor of Science in Speech and Drama", text: "Bachelor of Science in Speech and Drama" },
    { value: "Bachelor of Science in Speech Pathology", text: "Bachelor of Science in Speech Pathology" },
    { value: "Bachelor of Science in Statistics", text: "Bachelor of Science in Statistics" },
    { value: "Bachelor of Science in Sugar Technology", text: "Bachelor of Science in Sugar Technology" },
    { value: "Bachelor of Science in Supply Administration", text: "Bachelor of Science in Supply Administration" },
    { value: "Bachelor of Science in Supply Management", text: "Bachelor of Science in Supply Management" },
    { value: "Bachelor of Science in Teaching", text: "Bachelor of Science in Teaching" },
    { value: "Bachelor of Science in Teaching Arabic", text: "Bachelor of Science in Teaching Arabic" },
    { value: "Bachelor of Science in Technical Education", text: "Bachelor of Science in Technical Education" },
    { value: "Bachelor of Science in Technician Teacher Education", text: "Bachelor of Science in Technician Teacher Education" },
    { value: "Bachelor of Science in Technological Education", text: "Bachelor of Science in Technological Education" },
    { value: "Bachelor of Science in Textile Engineering", text: "Bachelor of Science in Textile Engineering" },
    { value: "Bachelor of Science in Theater Arts", text: "Bachelor of Science in Theater Arts" },
    { value: "Bachelor of Science in Theology", text: "Bachelor of Science in Theology" },
    { value: "Bachelor of Science in Tourism", text: "Bachelor of Science in Tourism" },
    { value: "Bachelor of Science in Tourism and Hotel Restaurant Management", text: "Bachelor of Science in Tourism and Hotel Restaurant Management" },
    { value: "Bachelor of Science in Tourism and Travel Management", text: "Bachelor of Science in Tourism and Travel Management" },
    { value: "Bachelor of Science in Town and Country Planning", text: "Bachelor of Science in Town and Country Planning" },
    { value: "Bachelor of Science in Trade Technology", text: "Bachelor of Science in Trade Technology" },
    { value: "Bachelor of Science in Upland Agricultural Entrepreneurship", text: "Bachelor of Science in Upland Agricultural Entrepreneurship" },
    { value: "Bachelor of Science in Veterinary Technology", text: "Bachelor of Science in Veterinary Technology" },
    { value: "Bachelor of Science in Volcanology", text: "Bachelor of Science in Volcanology" },
    { value: "Bachelor of Science in Zoology", text: "Bachelor of Science in Zoology" },
    { value: "Bachelor of Science Library", text: "Bachelor of Science Library" },
    { value: "Bachelor of Science Management Information System", text: "Bachelor of Science Management Information System" },
    { value: "Bachelor of Science Marine Technology", text: "Bachelor of Science Marine Technology" },
    { value: "Bachelor of Science Naval Architecture", text: "Bachelor of Science Naval Architecture" },
    { value: "Bachelor of Science Nursing and Community Health", text: "Bachelor of Science Nursing and Community Health" },
    { value: "Bachelor of Science Postal Management", text: "Bachelor of Science Postal Management" },
    { value: "Bachelor of Science Textile Garment Technology", text: "Bachelor of Science Textile Garment Technology" },
    { value: "Bachelor of Secondary Education", text: "Bachelor of Secondary Education" },
    { value: "Bachelor of Secondary Education Major in Physical Education", text: "Bachelor of Secondary Education Major in Physical Education" },
    { value: "Bachelor of Special Education", text: "Bachelor of Special Education" },
    { value: "Bachelor of Sports Science", text: "Bachelor of Sports Science" },
    { value: "Bachelor of Teaching Home Economics and Livehood Education", text: "Bachelor of Teaching Home Economics and Livehood Education" },
    { value: "Bachelor of Teaching Technology and Home Economics", text: "Bachelor of Teaching Technology and Home Economics" },
    { value: "Bachelor of Technical Teacher & Education", text: "Bachelor of Technical Teacher & Education" },
    { value: "Bachelor of Technology", text: "Bachelor of Technology" },
    { value: "Bachelor of Technology in Environmental Management", text: "Bachelor of Technology in Environmental Management" },
    { value: "Bachelor of Technology in Horticulture Management", text: "Bachelor of Technology in Horticulture Management" },
    { value: "Bachelor of Theology", text: "Bachelor of Theology" },
    { value: "Doctor in Biology", text: "Doctor in Biology" },
    { value: "Doctor in Business Management", text: "Doctor in Business Management" },
    { value: "Doctor in Development Administration", text: "Doctor in Development Administration" },
    { value: "Doctor in Education", text: "Doctor in Education" },
    { value: "Doctor in Educational Management/Administration", text: "Doctor in Educational Management/Administration" },
    { value: "Doctor in English", text: "Doctor in English" },
    { value: "Doctor in Management", text: "Doctor in Management" },
    { value: "Doctor in Plant Pathology", text: "Doctor in Plant Pathology" },
    { value: "Doctor in Psychology", text: "Doctor in Psychology" },
    { value: "Doctor in Technological Education", text: "Doctor in Technological Education" },
    { value: "Doctor in/of Public Administration", text: "Doctor in/of Public Administration" },
    { value: "Doctor of Agricultural Chemistry", text: "Doctor of Agricultural Chemistry" },
    { value: "Doctor of Agricultural Education", text: "Doctor of Agricultural Education" },
    { value: "Doctor of Agricultural Engineering", text: "Doctor of Agricultural Engineering" },
    { value: "Doctor of Agricultural Extension", text: "Doctor of Agricultural Extension" },
    { value: "Doctor of Arts", text: "Doctor of Arts" },
    { value: "Doctor of Arts in Language and Literature", text: "Doctor of Arts in Language and Literature" },
    { value: "Doctor of Business Administration", text: "Doctor of Business Administration" },
    { value: "Doctor of Business Technology", text: "Doctor of Business Technology" },
    { value: "Doctor of Civil Laws", text: "Doctor of Civil Laws" },
    { value: "Doctor of Dental Medicine", text: "Doctor of Dental Medicine" },
    { value: "Doctor of Education", text: "Doctor of Education" },
    { value: "Doctor of Education in Educational Administration", text: "Doctor of Education in Educational Administration" },
    { value: "Doctor of Education in Educational Management", text: "Doctor of Education in Educational Management" },
    { value: "Doctor of Education in Industrial Education Management", text: "Doctor of Education in Industrial Education Management" },
    { value: "Doctor of Letters", text: "Doctor of Letters" },
    { value: "Doctor of Mathematics Education", text: "Doctor of Mathematics Education" },
    { value: "Doctor of Medicine", text: "Doctor of Medicine" }
  ];