export const educationalLevels = [
    { value: "Grade 1", text: "Grade 1" },
    { value: "Grade 2", text: "Grade 2" },
    { value: "Grade 3", text: "Grade 3" },
    { value: "Grade 4", text: "Grade 4" },
    { value: "Grade 5", text: "Grade 5" },
    { value: "Grade 6", text: "Grade 6" },
    { value: "Elementary Graduate", text: "Elementary Graduate" },
    { value: "Grade 7", text: "Grade 7" },
    { value: "Grade 8", text: "Grade 8" },
    { value: "Grade 9", text: "Grade 9" },
    { value: "Grade 10", text: "Grade 10" },
    { value: "High School Graduate", text: "High School Graduate" },
    { value: "Grade 11", text: "Grade 11" },
    { value: "Grade 12", text: "Grade 12" },
    { value: "Senior High School Graduate", text: "Senior High School Graduate" },
    { value: "Vocational Undergraduate", text: "Vocational Undergraduate" },
    { value: "Vocational Graduate", text: "Vocational Graduate" },
    { value: "1st Year College", text: "1st Year College" },
    { value: "2nd Year College", text: "2nd Year College" },
    { value: "3rd Year College", text: "3rd Year College" },
    { value: "4th Year College", text: "4th Year College" },
    { value: "5th Year College", text: "5th Year College" },
    { value: "College Graduate", text: "College Graduate" },
    { value: "Post Graduate", text: "Post Graduate" },
];