export const industries = [
    { value: "Agriculture", text: "Agriculture" },
    { value: "ActivitiesOfPrivateHouseholds", text: "Activities Of Private Households As Employers And Undifferentiated Production Activities Of Private" },
    { value: "Construction", text: "Construction" },
    { value: "Education", text: "Education" },
    { value: "ElectricityGasAndWaterSupply", text: "Electricity, Gas And Water Supply" },
    { value: "ExtraTerritorialOrganizationsAndBodies", text: "Extra-Territorial Organizations And Bodies" },
    { value: "FinancialIntermediation", text: "Financial Intermediation" },
    { value: "Fishing", text: "Fishing" },
    { value: "HealthAndSocialWork", text: "Health And Social Work" },
    { value: "HotelsAndRestaurants", text: "Hotels And Restaurants" },
    { value: "IT", text: "IT BPO" },
    { value: "Manufacturing", text: "Manufacturing" },
    { value: "MiningAndQuarrying", text: "Mining And Quarrying" },
    { value: "OtherCommunitySocialAndPersonalServiceActivities", text: "Other Community, Social And Personal Service Activities" },
    { value: "PublicAdministrationAndDefense", text: "Public Administration And Defense" },
    { value: "RealEstateRentingAndBusinessActivities", text: "Real Estate, Renting And Business Activities" },
    { value: "TransportStorageAndCommunication", text: "Transport, Storage And Communication" },
    { value: "WholesaleAndRetailTrade", text: "Wholesale And Retail Trade" }
];